name: CI/CD Lesson

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-verison: 3.9
    - name:  Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest

    - name: Test with unittest
      run: | 
        python -m unittest discover -v
      

  
    
